import { Experience } from './types';

export const experienceData: Experience[] = [
  {
    id: 'senior-xr-dev-2024',
    company: 'MetaVision Technologies',
    position: 'Senior XR Developer',
    duration: {
      start: '2024-01',
      end: null, // Current position
    },
    location: 'San Francisco, CA (Remote)',
    companyLogo: '/images/companies/metavision.png',
    companyWebsite: 'https://metavision.tech',
    description: 'Leading XR development initiatives for enterprise clients, specializing in immersive training solutions and virtual collaboration platforms. Architecting scalable WebXR applications and mentoring junior developers.',
    achievements: [
      'Architected and delivered 3 major XR applications serving 10,000+ users',
      'Reduced application load times by 65% through advanced optimization techniques',
      'Led cross-functional team of 6 developers in agile XR development processes',
      'Implemented AI-driven gesture recognition system with 95% accuracy',
      'Established XR development best practices and code review standards',
    ],
    technologies: [
      'Unity 3D',
      'WebXR',
      'Three.js',
      'A-Frame',
      'Oculus SDK',
      'OpenXR',
      'C#',
      'TypeScript',
      'React',
      'Node.js',
      'WebGL',
      'GLSL',
    ],
    skillsGained: [
      'Technical Leadership',
      'XR Architecture Design',
      'Performance Optimization',
      'Team Mentoring',
      'Client Communication',
      'Project Planning',
    ],
    projectHighlights: [
      {
        name: 'VirtualTrain Pro',
        description: 'Enterprise VR training platform for manufacturing safety protocols',
        technologies: ['Unity 3D', 'Oculus SDK', 'C#', 'PostgreSQL'],
        impact: '40% reduction in workplace incidents for client companies',
        link: 'https://github.com/sharifbayoumy/virtualtrain-pro',
      },
      {
        name: 'CollabSpace WebXR',
        description: 'Browser-based virtual meeting rooms with spatial audio',
        technologies: ['WebXR', 'Three.js', 'WebRTC', 'Node.js'],
        impact: 'Deployed to 50+ organizations during COVID-19',
      },
      {
        name: 'AR Product Visualizer',
        description: 'E-commerce AR solution for furniture and home decor',
        technologies: ['ARCore', 'ARKit', 'Unity 3D', 'React Native'],
        impact: '25% increase in online sales conversion rates',
      },
    ],
    keyMetrics: [
      { label: 'Applications Delivered', value: '12+', description: 'Production XR applications' },
      { label: 'Users Served', value: '50K+', description: 'Across all platforms' },
      { label: 'Performance Improvement', value: '65%', description: 'Average load time reduction' },
      { label: 'Team Size', value: '6', description: 'Developers managed' },
    ],
  },
  {
    id: 'vr-app-dev-2022',
    company: 'ImmersiveWorks Studio',
    position: 'VR Application Developer',
    duration: {
      start: '2022-03',
      end: '2023-12',
    },
    location: 'Austin, TX',
    companyLogo: '/images/companies/immersiveworks.png',
    companyWebsite: 'https://immersiveworks.com',
    description: 'Developed cutting-edge VR applications for healthcare, education, and entertainment sectors. Specialized in Unity 3D development and cross-platform VR experiences.',
    achievements: [
      'Developed 8 VR applications with 4.8+ star ratings across platforms',
      'Implemented advanced haptic feedback systems for medical training',
      'Optimized VR performance achieving 90+ FPS on mid-range hardware',
      'Collaborated with UX designers to create intuitive VR interfaces',
      'Mentored 3 junior developers in VR best practices',
    ],
    technologies: [
      'Unity 3D',
      'C#',
      'Oculus SDK',
      'SteamVR',
      'VRTK',
      'Blender',
      'Photon',
      'Mirror Networking',
      'FMOD',
      'Git',
      'Jenkins',
    ],
    skillsGained: [
      'VR User Experience Design',
      'Performance Optimization',
      'Cross-platform Development',
      'Haptic Feedback Systems',
      'Multiplayer VR Architecture',
    ],
    projectHighlights: [
      {
        name: 'MedVR Simulator',
        description: 'VR surgery training simulator for medical students',
        technologies: ['Unity 3D', 'Oculus SDK', 'C#', 'Haptic SDK'],
        impact: 'Adopted by 15+ medical schools worldwide',
      },
      {
        name: 'EduSpace VR',
        description: 'Virtual classroom environments for remote learning',
        technologies: ['Unity 3D', 'Photon', 'WebRTC', 'C#'],
        impact: 'Used by 5,000+ students during remote learning',
      },
      {
        name: 'Adventure Quest VR',
        description: 'Multiplayer fantasy adventure game in VR',
        technologies: ['Unity 3D', 'Mirror Networking', 'FMOD', 'C#'],
        impact: '100K+ downloads on Steam and Oculus Store',
      },
    ],
    keyMetrics: [
      { label: 'VR Apps Developed', value: '8', description: 'Published applications' },
      { label: 'Average Rating', value: '4.8/5', description: 'User satisfaction score' },
      { label: 'Frame Rate', value: '90+ FPS', description: 'Performance optimization target' },
      { label: 'Downloads', value: '150K+', description: 'Total across all platforms' },
    ],
  },
  {
    id: 'fullstack-dev-2020',
    company: 'TechNova Solutions',
    position: 'Full-Stack Developer',
    duration: {
      start: '2020-06',
      end: '2022-02',
    },
    location: 'New York, NY',
    companyLogo: '/images/companies/technova.png',
    companyWebsite: 'https://technova-solutions.com',
    description: 'Built scalable web applications and APIs for diverse clients. Gained expertise in modern web technologies and cloud deployment while contributing to multiple full-stack projects.',
    achievements: [
      'Developed and deployed 15+ web applications with 99.9% uptime',
      'Built RESTful APIs serving 1M+ requests per day',
      'Implemented CI/CD pipelines reducing deployment time by 80%',
      'Led migration from monolith to microservices architecture',
      'Achieved 95+ Lighthouse scores on all production applications',
    ],
    technologies: [
      'React',
      'Node.js',
      'TypeScript',
      'PostgreSQL',
      'MongoDB',
      'AWS',
      'Docker',
      'Kubernetes',
      'GraphQL',
      'Redux',
      'Express.js',
      'Jest',
    ],
    skillsGained: [
      'Full-Stack Architecture',
      'Cloud Deployment',
      'Database Design',
      'API Development',
      'DevOps Practices',
      'Agile Methodology',
    ],
    projectHighlights: [
      {
        name: 'E-Commerce Platform',
        description: 'Scalable online marketplace with real-time inventory',
        technologies: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'AWS'],
        impact: 'Processed $2M+ in transactions in first year',
      },
      {
        name: 'Real-Time Analytics Dashboard',
        description: 'Business intelligence platform with live data visualization',
        technologies: ['React', 'D3.js', 'WebSocket', 'InfluxDB'],
        impact: 'Improved decision-making speed by 60%',
      },
      {
        name: 'Social Learning Platform',
        description: 'Educational platform with video streaming and collaboration',
        technologies: ['React', 'Node.js', 'WebRTC', 'MongoDB'],
        impact: '10K+ active users within 6 months',
      },
    ],
    keyMetrics: [
      { label: 'Applications Built', value: '15+', description: 'Production web applications' },
      { label: 'API Requests', value: '1M+/day', description: 'Peak traffic handled' },
      { label: 'Uptime', value: '99.9%', description: 'Service reliability' },
      { label: 'Performance Score', value: '95+', description: 'Lighthouse score average' },
    ],
  },
  {
    id: 'junior-game-dev-2019',
    company: 'PixelCraft Games',
    position: 'Junior Game Developer',
    duration: {
      start: '2019-01',
      end: '2020-05',
    },
    location: 'Los Angeles, CA',
    companyLogo: '/images/companies/pixelcraft.png',
    companyWebsite: 'https://pixelcraft-games.com',
    description: 'Started my professional journey in game development, contributing to mobile and PC games. Learned fundamental programming concepts and game development workflows.',
    achievements: [
      'Contributed to 4 published games with 500K+ combined downloads',
      'Implemented gameplay mechanics and UI systems',
      'Optimized game performance for mobile devices',
      'Collaborated with artists and designers in agile sprints',
      'Learned industry-standard game development practices',
    ],
    technologies: [
      'Unity 3D',
      'C#',
      'JavaScript',
      'HTML5 Canvas',
      'SQLite',
      'Git',
      'Visual Studio',
      'Photoshop',
      'Maya (basics)',
    ],
    skillsGained: [
      'Game Development Fundamentals',
      'Object-Oriented Programming',
      'Version Control',
      'Team Collaboration',
      'Problem Solving',
      'Game Design Principles',
    ],
    projectHighlights: [
      {
        name: 'Puzzle Adventures',
        description: 'Mobile puzzle game with physics-based mechanics',
        technologies: ['Unity 3D', 'C#', 'SQLite'],
        impact: '250K+ downloads on Google Play and App Store',
      },
      {
        name: 'Space Runner 2D',
        description: 'Endless runner game with procedural generation',
        technologies: ['Unity 3D', 'C#', 'Unity Analytics'],
        impact: '150K+ downloads, featured on Play Store',
      },
      {
        name: 'Web Mini-Games',
        description: 'Collection of HTML5 browser games',
        technologies: ['JavaScript', 'HTML5 Canvas', 'WebGL'],
        impact: '100K+ monthly active players',
      },
    ],
    keyMetrics: [
      { label: 'Games Published', value: '4', description: 'Commercial game releases' },
      { label: 'Total Downloads', value: '500K+', description: 'Across all platforms' },
      { label: 'Code Contributions', value: '1,200+', description: 'Git commits' },
      { label: 'Learning Milestones', value: '25+', description: 'Technical skills acquired' },
    ],
  },
];